name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: ( docker pull paulfrischknecht/cling || true ) && docker build . --file Dockerfile --tag paulfrischknecht/cling --cache-from paulfrischknecht/cling
    
    - name: Push the Docker image
      run: echo ${{ secrets.PAULFRISCHKNECHT_DOCKER_IO_PASSWORD }} | docker login --username paulfrischknecht --password-stdin docker.io && docker push paulfrischknecht/cling && docker logout

